sudo: false
language: ruby
rvm:
  - 2.1

before_install:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin

install:
  - make deps
script:
  - make site

env:
  global:
  - secure: nZU0dpuktm9+uJlrvpoHIQS3jQD5rWj3dyz1xY/XpFqt+LGWVOqDGwrXXQ2NMx5mBAkFJrtYP88DQDakTBh+A92bpZsyyWi62qHAII3xEAK/Ot6akLoRJ7Jbl09eCbb6uj1Cwwf2TMi/yQgT8kcmJtbQjCmwAKSb0dDNLYihEmpqL2Mx1eHIzp+hZ7xKeCXYMcayRSVK/mJop3vV0JU7+qQj+oYsvJ4iTeZuiwbtdUvc+9AcKQCS98HJqKcdiFLD4LayZj/R5+LgkLchynv2ogE3TUhONk1ZU/Mg9W5qAlz4v83Dfwep4wP+j4Oe1ORy2p1ba7kV+NHYl9CsBAe3n86FiPTwiufn9DTmYv0JhIVrtePPSVa7EhAngXvgr23ELFGKoQdUx7T4fucMfL3KpOKF48ZSrkg+e4HxMbSWDR+gRL5w3ckKavwLMQm3MPUjPLIDaa1lqA3U7Qz2Fz18ZGH9LPXqjJKhU7Q4dehE0KdbWQ32JLMXkOmcX5WCMsZvQsuy7zW1HHDQqorQHRrSQ/gTs1PjeL+HIAV5HTlP5d6vH7uU4mN+F9ubocayL5Z6mEuN81rH0RhlAYHlnu9SQxEltm/x2FS8Xtnrzo9MT9banbdq2+GR7j5NOqX89oXuR2MopUVvaUdGs5lz37C+ViQDmn6GFSncOmM1Y+F1Jcs=
  - secure: SUmnMNimG0BfaNcasOY4U4ka4uzxVqEF4Tpox4eo07Lk1yknRLTZl6FdMApJC4G4JlRaME/gCF6EH1TGm7AizqfsjytDjsiMYzllXTEexU4eZiWnknFKVioDWCa7URXcuo28lM17cVA4wUI1GxBDLiO9lBvau4HiXz5+zD47m/78WQYXqnNdLvsUI8SFRSZExob35ez0hSI/KJQHuuFwOWCbV1ymXsYpfw7Ii3zKep/WcztbAsgti/cRdatnx0aJkxB/h0e/+dXB8nEbakUVsJhTtGW6aqgVn/In2N+tViBTXeyFHJgX3lzCmnHezLTR/95MoC7hQL5BLgqFgxaMwaRuUAmZvEpx8WN1iq4mjmkl5TM3VQFzPfgsIxn2CJWSW6hnW+aIXaw/uCwY659B6WczdbK13odfek3qRlNBm2CWqcTQ8C8UWG3JGfNmqMtTTDaivVxrkFC4/OUQR0UmJRe3pXF/ycgX05nKxX0FMwTHczU/eo6Q3nxyOLEhaHjwC/AiUhcolsTJcuwBQ4SdiRBxU7/sB9v/6PLy1Rwr7DEQMDSveP1RowFAlhgPhmTlw53EkS10/tSAiXbSE3z3zo5wlR5GbZfsFHSXbITaP42o6y16frUChm8gkX1Aa2580CIfbsrEmJ0iHwOpNQd8htlxnWVaF4WZOilLK36WTN0=

after_success:
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_BRANCH" == "staging" ]; then make stage; fi
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_BRANCH" == "master" ];  then make prod; fi
