# External gems
gems:
  - jekyll-sitemap
  - jekyll-archives
  - jekyll-paginate

exclude:
  - "/vendor/"

# Site settings
title: Tech Blog
subtitle: "Blogging So I Don't Forget"
name:  Andrew Kroh
email: andrew.kroh@crowbird.com
description: >
  I am Andrew Kroh, a software engineer from northern Virginia.
url: "https://www.andrewkroh.com"
# Base URL of site (i.e. /blog). It should always start with a slash,
# and never end with a slash. Set it to a blank value if hosting at the
# root of your server.
baseurl:
cover: "/assets/header_image.jpg"
logo: "/assets/logo.png"

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  # REF: http://stackoverflow.com/a/25597026/503798
  smart_quotes: ["apos", "apos", "quot", "quot"]
paginate: 5
paginate_path: "/page:num/"

# Archive settings (see https://github.com/jekyll/jekyll-archives/)
jekyll-archives:
  enabled:
    - categories
    - tags
  layout: 'archive'
  permalinks:
    category: '/category/:name/'
    tag: '/tag/:name/'

# Disqus comments
disqus_disabled:  true
#disqus_shortname: andrewkroh

# Google analytics
ga_tracking_id: "UA-9602738-7"

# Category descriptions (for archive pages)
descriptions:
  - cat: solaris
    desc: Solaris operating system

# Social icons and sharing options
#
# Social settings are used in two places:
# * In the footer, as links to your personal profiles
# * After each blog post for sharing widgets
#
# social:
#   - name: Twitter                         # Name of the service
#     icon: twitter                         # Font Awesome icon to use (minus fa- prefix)
#     username: "@TheBenCentra"             # (User) Name to display in the footer link
#     url: https://twitter.com/TheBenCentra # URL of your profile (leave blank to not display in footer)
#     desc: Follow me on Twitter            # Description to display as link title, etc
#     share: true                           # Include in the "Share" section of posts
social:
  - name: Twitter
    icon: twitter
    username: krohbird
    url: https://twitter.com/krohbird
    desc: Follow me on Twitter
    share: true

  - name: GitHub
    icon: github
    username: andrewkroh
    url: https://github.com/andrewkroh
    desc: Fork me on GitHub
    share: false

  - name: YouTube
    icon: youtube
    username: crowbird01
    url: https://www.youtube.com/user/crowbird01
    desc: Subscribe on YouTube
    share: false

  - name: Instagram
    icon: instagram
    username: krohbird
    url: https://instagram.com/krohbird/
    desc: Follow me on Instagram
    share: false

# Social sharing protocols
# These are for automatically generating sharing metadata for FB and Twitter
# OS Protocol is for sharing the source of your site, if you're interested. For more, see osprotocol.com
protocols:
  twitter_image: "/assets/logo.png"
#    fb_image: "/assets/logo.png"
#    fb_image_width: 612
#    fb_image_height: 605
#    fb_image_type: "image/png"
#
#    os_repo: "https://github.com/RichardLitt/wordhoardpress.com"
#    os_rcs_type: "git"
#    os_src: "git@github.com:RichardLitt/wordhoardpress.com.git"
